autocode:
  root: /root/go/coding
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
db-list:
- disable: false
  type: ""
  alias-name: ""
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
jwt:
  signing-key: adcat
  expires-time: 57600
  buffer-time: 3600
  issuer: adcat
local:
  path: uploads/file
mysql:
  path: test-mysql.adcat.cc
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: go_admin
  username: test_sh
  password: test!1234
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
redis:
  db: 0
  addr: ""
  password: ""
system:
  env: develop
  addr: 9101
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
timer:
  start: false
  spec: ""
  detail: []
zap:
  level: debug
  format: console
  prefix: '[go-admin]'
  director: tmp/logs
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
