# zap logger configuration
zap:
  level: 'debug'
  format: 'console'
  prefix: '[go-admin]'
  director: 'tmp/logs'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql connect configuration
mysql:
  path: 'test-mysql.adcat.cc'
  port: '3306'
  config: ''
  db-name: 'go_admin'
  username: 'test_sh'
  password: 'test!1234'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# pgsql connect configuration
pgsql:
  path: ''
  port: ''
  config: ''
  db-name: ''
  username: ''
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

db-list: [
  {
    disabled: true, # 是否启用
    type: "", # 数据库的类型,目前支持mysql、pgsql
    alias-name: "", # 数据库的名称,注意: alias-name 需要在db-list中唯一
    path: '',
    port: '',
    config: '',
    db-name: '',
    username: '',
    password: '',
    max-idle-conns: 10,
    max-open-conns: 100,
    log-mode: "",
    log-zap: false,
  }
]

# local configuration
local:
  path: 'uploads/file'

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# system config
system:
  env: 'develop' # Change to "develop" to skip authentication for development mode
  addr: 9101
  db-type: 'mysql'
  oss-type: 'local'
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600

# jwt configuration
jwt:
  signing-key: 'adcat'
  expires-time: 57600
  buffer-time: 3600
  issuer: 'adcat'