# zap logger configuration
zap:
  level: 'debug'
  format: 'console'
  prefix: '[go-admin]'
  director: 'tmp/logs'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true