# zap logger configuration
zap:
  level: 'debug'
  format: 'console'
  prefix: '[go-admin]'
  director: 'tmp/logs'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql connect configuration
mysql:
  path: 'test-mysql.adcat.cc'
  port: '3306'
  config: ''
  db-name: 'go_admin'
  username: 'test_sh'
  password: 'test!1234'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# pgsql connect configuration
pgsql:
  path: ''
  port: ''
  config: ''
  db-name: ''
  username: ''
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

db-list: [
  {
    disabled: true, # 是否启用
    type: "", # 数据库的类型,目前支持mysql、pgsql
    alias-name: "", # 数据库的名称,注意: alias-name 需要在db-list中唯一
    path: '',
    port: '',
    config: '',
    db-name: '',
    username: '',
    password: '',
    max-idle-conns: 10,
    max-open-conns: 100,
    log-mode: "",
    log-zap: false,
  }
]